Removed extra empty lines and commented codes, formatted files.
1thing-org/1thing.org pull request #191
Opened 2024-01-27 06:32 UTC by jiayingxie

Removed extra empty lines and commented codes, formatted files.

2024-02-01 19:59 UTC, jin-qin requested changes

2024-02-01 19:59 UTC, jin-qin commented on src/components/actions/navbaraction/NavAction.css
redundant line.

2024-02-01 19:59 UTC, jin-qin commented on src/components/actions/navbaraction/NavAction.css
> +
redundant line.

2024-02-04 06:02 UTC, rayhm6419 approved these changes

2024-02-16 02:06 UTC, lima01 approved these changes

2024-02-16 02:07 UTC, lima01 approved these changes

2024-02-16 02:07 UTC, merged